debug: true
server:
  port: 8848

spring:
  profiles:
    active: dev
  application:
    name: example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ahcloud-test.com:3306/saas_contract?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=Asia/Shanghai
    username: root
    password: 1qazCDE#5tgb
# 过滤指定类 autoconfigure.exclude:
